spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/laundrydb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE #jdbc:h2:file:./data/laundrydb
    username: sa
    password:

  thymeleaf:
      cache: false   # 캐싱 끄기

  jpa:
    hibernate:
      ddl-auto: update   # ?? ??? update ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        id.new_generator_mappings: false

  h2:
    console:
      enabled: true
      path: /h2-console

  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  sql:
    init:
      mode: always              # schema.sql 자동 실행되도록